name: pavi
favicon: null
layout_spectrum: 0.963177667465061
typography_spectrum: 0.18036941136233509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9665003714617342
  lightness: 0.7531052050180733
  saturation: 0.6207158018369228
  rhythmicContrast: 0.4854786521755159
purpose: []
